"""Normalized response models for generation endpoints."""

from pydantic import BaseModel, Field


class Usage(BaseModel):
    """Token consumption statistics."""

    input_tokens: int = Field(..., ge=0, description="Tokens in the prompt.")
    output_tokens: int = Field(..., ge=0, description="Tokens generated in the completion.")
    total_tokens: int = Field(..., ge=0, description="Total tokens consumed.")


class LLMResponse(BaseModel):
    """Normalized response returned to API clients regardless of upstream provider."""

    request_id: str = Field(..., description="Unique correlation ID for tracing this request.")
    provider: str = Field(
        ..., description="Provider that serviced the request (e.g. 'openai', 'anthropic')."
    )
    model: str = Field(..., description="Model identifier used for generation.")
    content: str = Field(..., description="Text content generated by the model.")
    input_tokens: int = Field(..., ge=0, description="Number of tokens in the prompt.")
    output_tokens: int = Field(..., ge=0, description="Number of tokens generated.")
    total_tokens: int = Field(..., ge=0, description="Total tokens consumed.")
    finish_reason: str = Field(
        ...,
        description="Reason generation terminated (e.g. 'stop', 'length', 'tool_calls').",
    )
    latency_ms: float = Field(
        ...,
        ge=0.0,
        description="End-to-end execution latency for the upstream call in milliseconds.",
    )
